// example/wc-angular/src/app/testcomp-angular/testcomp-angular.component.ts
import {Component, OnInit, ViewEncapsulation} from '@angular/core';

@Component({
  selector: 'custom-testcomp-angular',
  template: `
    <div id="angulartest">
      <h2>En Angular-basert Web Component</h2>
      <a href="https://www.techiediaries.com/angular-elements-web-components/">Fin guide for å lage Web Components med
        Angular</a>
      <p>Intern teller = <b>{{counter}}</b></p>
      <p>Ekstern teller = <b>{{eksternCounter}}</b></p>
      <button (click)="handleClick()">Intern +1</button>
      <button (click)="dispatch()">Ekstern +1</button>
    </div>
  `,
  styles: [
      `#angulartest {
      border-style: solid;
      border-color: #b52e30;
    }`
  ],
  host: {
    '(window:react:clicked)': 'handleChange()',
    '(window:vue:clicked)': 'handleChange()',
    '(window:js:clicked)': 'handleChange()'
  },
  encapsulation: ViewEncapsulation.Native
})
export class TestcompAngularComponent implements OnInit {
  counter = 0;
  eksternCounter = 0;

  constructor() {
  }

  handleClick() {
    this.counter += 1;
  }

  handleChange() {
    this.eksternCounter += 1;
  }

  dispatch() {
    console.log('Angular-komponent: Event dispatched: angular:clicked');
    window.dispatchEvent(new CustomEvent('angular:clicked', {
      bubbles: true,
    }));
  }

  ngOnInit() {
  }

}

// example/wc-vue/src/components/testcomp-vue.vue
<style scoped>

    #vue-component {
        border-style: solid;
        border-color: #41b883;
    }

</style>

<template>

    <div id="vue-component">
        <h2>En Vue-basert Web Component</h2>
        <p>Intern teller = <b>{{counter}}</b></p>
        <p>Ekstern teller = <b>{{externalCounter}}</b></p>
        <button v-on:click="counter += 1">Intern +1</button>
        <button v-on:click="dispatch">Ekstern +1</button>
    </div>

</template>

<script>

    export default {
        name: 'TestComp',

        mounted() {
            window.addEventListener('js:clicked', this.handleChange);
            window.addEventListener('react:clicked', this.handleChange);
            window.addEventListener('angular:clicked', this.handleChange);
        },

        destroyed() {
            window.removeEventListener('js:clicked', this.handleChange);
            window.removeEventListener('react:clicked', this.handleChange);
            window.removeEventListener('angular:clicked', this.handleChange);
        },

        data() {
            return {
                counter: 0,
                externalCounter: 0
            }
        },

        methods: {
            handleChange: function () {
                console.log('Vue-komponent: Event mottatt: clicked');
                this.externalCounter += 1;
            },

            dispatch: function () {
                console.log('Vue-komponent: Event dispatched: vue:clicked');
                window.dispatchEvent(new CustomEvent('vue:clicked', {
                    bubbles: true,
                }));
            }
        }
    }

</script>
